language: en
pipeline:  pretrained_embeddings_spacy
policies:
- name: MemoizationPolicy
  max_history: 5
- name: KerasPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.4
  core_threshold: 0.3
  fallback_action_name: "action_default_fallback"
